import os

DEFAULT_SAMPLE_RATE = 44100
DEFAULT_FRAME_LENGTH = 800
DEFAULT_HOP_LENGTH = 5000

REPO_ROOT = os.path.dirname(os.path.dirname(__file__))

# GP Hyperparameters
DEFAULT_M = 9
DEFAULT_SIGMA_F = 0.005
DEFAULT_SIGMA_N = 10
DEFAULT_V = 2.37
DEFAULT_T = 0.465
